/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GroupOrdersRouteImport } from './routes/group-orders'
import { Route as IndexRouteImport } from './routes/index'

const GroupOrdersRoute = GroupOrdersRouteImport.update({
  id: '/group-orders',
  path: '/group-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/group-orders': typeof GroupOrdersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/group-orders': typeof GroupOrdersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/group-orders': typeof GroupOrdersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/group-orders'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/group-orders'
  id: '__root__' | '/' | '/group-orders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GroupOrdersRoute: typeof GroupOrdersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/group-orders': {
      id: '/group-orders'
      path: '/group-orders'
      fullPath: '/group-orders'
      preLoaderRoute: typeof GroupOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GroupOrdersRoute: GroupOrdersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
