/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GroupOrdersRouteImport } from './routes/group-orders'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GroupOrdersCampaignIdRouteImport } from './routes/group-orders.$campaignId'
import { Route as AdminLoginRouteImport } from './routes/admin.login'

const GroupOrdersRoute = GroupOrdersRouteImport.update({
  id: '/group-orders',
  path: '/group-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupOrdersCampaignIdRoute = GroupOrdersCampaignIdRouteImport.update({
  id: '/$campaignId',
  path: '/$campaignId',
  getParentRoute: () => GroupOrdersRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/group-orders': typeof GroupOrdersRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/group-orders/$campaignId': typeof GroupOrdersCampaignIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/group-orders': typeof GroupOrdersRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/group-orders/$campaignId': typeof GroupOrdersCampaignIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/group-orders': typeof GroupOrdersRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/group-orders/$campaignId': typeof GroupOrdersCampaignIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/group-orders'
    | '/admin/login'
    | '/group-orders/$campaignId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/group-orders' | '/admin/login' | '/group-orders/$campaignId'
  id:
    | '__root__'
    | '/'
    | '/group-orders'
    | '/admin/login'
    | '/group-orders/$campaignId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GroupOrdersRoute: typeof GroupOrdersRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/group-orders': {
      id: '/group-orders'
      path: '/group-orders'
      fullPath: '/group-orders'
      preLoaderRoute: typeof GroupOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group-orders/$campaignId': {
      id: '/group-orders/$campaignId'
      path: '/$campaignId'
      fullPath: '/group-orders/$campaignId'
      preLoaderRoute: typeof GroupOrdersCampaignIdRouteImport
      parentRoute: typeof GroupOrdersRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GroupOrdersRouteChildren {
  GroupOrdersCampaignIdRoute: typeof GroupOrdersCampaignIdRoute
}

const GroupOrdersRouteChildren: GroupOrdersRouteChildren = {
  GroupOrdersCampaignIdRoute: GroupOrdersCampaignIdRoute,
}

const GroupOrdersRouteWithChildren = GroupOrdersRoute._addFileChildren(
  GroupOrdersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GroupOrdersRoute: GroupOrdersRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
